version: '3.3'

services:
  reprocess-mediator:
    image: jembi/reprocess-mediator-mvp:latest
    container_name: reprocess-mediator
    environment:
      - ES_URL=http://es-analytics:9200
      - LOGSTASH_URL=http://logstash:5066/fhir

  mpi-mediator:
    image: jembi/mpi-mediator
    container_name: mpi-mediator
    environment:
      - CR_URL=http://opencr:3000/fhir
      - SHR_URL=http://hapi-fhir:8080/fhir
      - OPENHIM_CLIENT_ID=test
      - PATIENT_REF_TO_USE_IN_SHR=LOCAL

volumes:
  instant:
    external: true
