apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.hapi.yml
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: fhir
  name: fhir
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fhir
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.hapi.yml
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: fhir
    spec:
      containers:
        - env:
            - name: profiles.active
              value: r4
            - name: spring.datasource.driverClassName
              value: org.postgresql.Driver
            - name: spring.datasource.password
              value: admin
            - name: spring.datasource.url
              value: jdbc:postgresql://db:5432/hapi
            - name: spring.datasource.username
              value: admin
          image: hapiproject/hapi:latest
          name: fhir
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /data/hapi
              name: hapi-data
      restartPolicy: Always
      volumes:
        - name: hapi-data
          persistentVolumeClaim:
            claimName: hapi-data
status: {}
