apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f packages/data-pipeline/docker/docker-compose.yml -o packages/data-pipeline/kubernetes/main/
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logstash
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f packages/data-pipeline/docker/docker-compose.yml -o packages/data-pipeline/kubernetes/main/
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: logstash
    spec:
      containers:
        - image: docker.elastic.co/logstash/logstash:7.6.2
          name: logstash
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/logstash/pipeline/
              name: logstash-pipeline
            - mountPath: /usr/share/logstash/config/
              name: logstash-config
      restartPolicy: Always
      volumes:
        - name: logstash-pipeline
          configMap:
            name: logstash-pipeline-configmap
        - name: logstash-config
          configMap:
            name: logstash-config-configmap
status: {}
